blank_issues_enabled: true
contact_links:
  - name: Bug Report
    description: File a bug report
    title: "[BUG] "
    labels: [ "bug", ]
    body:
      - type: textarea
        id: expected-behavior
        attributes:
          label: Expected behavior
          description: A clear and concise description of what you expected to happen.
          placeholder: ...
        validations:
          required: true
      - type: textarea
        id: problem
        attributes:
          label: Describe the bug
          description: A clear and concise description of what the bug is.
          placeholder: ...
      - type: textarea
        id: version
        attributes:
          label: Versions
          description: Relevant versions of delicatessen, OS, Python, and dependencies
          placeholder: OS; v..., Python; 3., Delicatessen; ..., NumPy; v...; SciPy; ...
      - type: textarea
        id: error-log
        attributes:
          label: Relevant error output
          description: Please copy and paste any relevant error or log output. This will be automatically formatted into code, so no need for backticks.
          render: shell
      - type: textarea
        id: add-context
        attributes:
          label: Additional context
          description: Add any other context about the problem here.
          placeholder: None
